# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_torch.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12remote_torch.proto\x12\x0cremote_torch\"\x1f\n\tReference\x12\x12\n\nidentifier\x18\x01 \x01(\t\"~\n\rReferenceMode\x12)\n\x08\x61rtifact\x18\x01 \x01(\x0b\x32\x17.remote_torch.Reference\x12\x14\n\x0c\x61\x63\x63\x65ss_group\x18\x02 \x01(\t\x12\x0c\n\x04read\x18\x03 \x01(\x08\x12\r\n\x05write\x18\x04 \x01(\x08\x12\x0f\n\x07\x65xecute\x18\x05 \x01(\x08\",\n\x05Users\x12\x14\n\x0c\x61\x63\x63\x65ss_group\x18\x01 \x01(\t\x12\r\n\x05users\x18\x02 \x03(\t\"\x15\n\x05\x43hunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x07\n\x05\x45mpty\"\x9a\x01\n\x0bTrainConfig\x12&\n\x05model\x18\x01 \x01(\x0b\x32\x17.remote_torch.Reference\x12(\n\x07\x64\x61taset\x18\x02 \x01(\x0b\x32\x17.remote_torch.Reference\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\x12\x0e\n\x06\x65pochs\x18\x04 \x01(\x05\x12\x15\n\rlearning_rate\x18\x05 \x01(\x02\"u\n\rPredictConfig\x12&\n\x05model\x18\x01 \x01(\x0b\x32\x17.remote_torch.Reference\x12(\n\x07\x64\x61taset\x18\x02 \x01(\x0b\x32\x17.remote_torch.Reference\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\"\x19\n\x08\x41\x63\x63uracy\x12\r\n\x05value\x18\x01 \x01(\x02\x32\x8a\x04\n\x11ReferenceProtocol\x12<\n\x08SendData\x12\x13.remote_torch.Chunk\x1a\x17.remote_torch.Reference\"\x00(\x01\x12=\n\tSendModel\x12\x13.remote_torch.Chunk\x1a\x17.remote_torch.Reference\"\x00(\x01\x12\x39\n\x05\x46\x65tch\x12\x17.remote_torch.Reference\x1a\x13.remote_torch.Chunk\"\x00\x30\x01\x12=\n\x0b\x44\x65leteModel\x12\x17.remote_torch.Reference\x1a\x13.remote_torch.Empty\"\x00\x12=\n\x0b\x44\x65leteBatch\x12\x17.remote_torch.Reference\x1a\x13.remote_torch.Empty\"\x00\x12=\n\x05Train\x12\x19.remote_torch.TrainConfig\x1a\x17.remote_torch.Reference\"\x00\x12\x41\n\x07Predict\x12\x1b.remote_torch.PredictConfig\x1a\x17.remote_torch.Reference\"\x00\x12=\n\x04Test\x12\x1b.remote_torch.PredictConfig\x1a\x16.remote_torch.Accuracy\"\x00\x62\x06proto3')



_REFERENCE = DESCRIPTOR.message_types_by_name['Reference']
_REFERENCEMODE = DESCRIPTOR.message_types_by_name['ReferenceMode']
_USERS = DESCRIPTOR.message_types_by_name['Users']
_CHUNK = DESCRIPTOR.message_types_by_name['Chunk']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_TRAINCONFIG = DESCRIPTOR.message_types_by_name['TrainConfig']
_PREDICTCONFIG = DESCRIPTOR.message_types_by_name['PredictConfig']
_ACCURACY = DESCRIPTOR.message_types_by_name['Accuracy']
Reference = _reflection.GeneratedProtocolMessageType('Reference', (_message.Message,), {
  'DESCRIPTOR' : _REFERENCE,
  '__module__' : 'remote_torch_pb2'
  # @@protoc_insertion_point(class_scope:remote_torch.Reference)
  })
_sym_db.RegisterMessage(Reference)

ReferenceMode = _reflection.GeneratedProtocolMessageType('ReferenceMode', (_message.Message,), {
  'DESCRIPTOR' : _REFERENCEMODE,
  '__module__' : 'remote_torch_pb2'
  # @@protoc_insertion_point(class_scope:remote_torch.ReferenceMode)
  })
_sym_db.RegisterMessage(ReferenceMode)

Users = _reflection.GeneratedProtocolMessageType('Users', (_message.Message,), {
  'DESCRIPTOR' : _USERS,
  '__module__' : 'remote_torch_pb2'
  # @@protoc_insertion_point(class_scope:remote_torch.Users)
  })
_sym_db.RegisterMessage(Users)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), {
  'DESCRIPTOR' : _CHUNK,
  '__module__' : 'remote_torch_pb2'
  # @@protoc_insertion_point(class_scope:remote_torch.Chunk)
  })
_sym_db.RegisterMessage(Chunk)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'remote_torch_pb2'
  # @@protoc_insertion_point(class_scope:remote_torch.Empty)
  })
_sym_db.RegisterMessage(Empty)

TrainConfig = _reflection.GeneratedProtocolMessageType('TrainConfig', (_message.Message,), {
  'DESCRIPTOR' : _TRAINCONFIG,
  '__module__' : 'remote_torch_pb2'
  # @@protoc_insertion_point(class_scope:remote_torch.TrainConfig)
  })
_sym_db.RegisterMessage(TrainConfig)

PredictConfig = _reflection.GeneratedProtocolMessageType('PredictConfig', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTCONFIG,
  '__module__' : 'remote_torch_pb2'
  # @@protoc_insertion_point(class_scope:remote_torch.PredictConfig)
  })
_sym_db.RegisterMessage(PredictConfig)

Accuracy = _reflection.GeneratedProtocolMessageType('Accuracy', (_message.Message,), {
  'DESCRIPTOR' : _ACCURACY,
  '__module__' : 'remote_torch_pb2'
  # @@protoc_insertion_point(class_scope:remote_torch.Accuracy)
  })
_sym_db.RegisterMessage(Accuracy)

_REFERENCEPROTOCOL = DESCRIPTOR.services_by_name['ReferenceProtocol']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REFERENCE._serialized_start=36
  _REFERENCE._serialized_end=67
  _REFERENCEMODE._serialized_start=69
  _REFERENCEMODE._serialized_end=195
  _USERS._serialized_start=197
  _USERS._serialized_end=241
  _CHUNK._serialized_start=243
  _CHUNK._serialized_end=264
  _EMPTY._serialized_start=266
  _EMPTY._serialized_end=273
  _TRAINCONFIG._serialized_start=276
  _TRAINCONFIG._serialized_end=430
  _PREDICTCONFIG._serialized_start=432
  _PREDICTCONFIG._serialized_end=549
  _ACCURACY._serialized_start=551
  _ACCURACY._serialized_end=576
  _REFERENCEPROTOCOL._serialized_start=579
  _REFERENCEPROTOCOL._serialized_end=1101
# @@protoc_insertion_point(module_scope)
