site_name: "BastionAI"

site_url: https://www.mithrilsecurity.io/

repo_url: https://github.com/mithril-security/bastionai

theme:
  name: material
  custom_dir: docs/material_theme_customization
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
    - scheme: default
      toggle:
        icon: material/weather-night

extra:
  homepage: https://mithrilsecurity.io

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - 'https://code.jquery.com/jquery-3.3.1.min.js'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
- search

nav:
  - Home: "index.md"
  - "Getting Started":
      - 'getting-started/quick-start.md'
  - "Client API reference": "resources/bastionai/client.html"
