# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import remote_torch_pb2 as remote__torch__pb2


class RemoteTorchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendDataset = channel.stream_unary(
                '/remote_torch.RemoteTorch/SendDataset',
                request_serializer=remote__torch__pb2.Chunk.SerializeToString,
                response_deserializer=remote__torch__pb2.Reference.FromString,
                )
        self.SendModel = channel.stream_unary(
                '/remote_torch.RemoteTorch/SendModel',
                request_serializer=remote__torch__pb2.Chunk.SerializeToString,
                response_deserializer=remote__torch__pb2.Reference.FromString,
                )
        self.FetchDataset = channel.unary_stream(
                '/remote_torch.RemoteTorch/FetchDataset',
                request_serializer=remote__torch__pb2.Reference.SerializeToString,
                response_deserializer=remote__torch__pb2.Chunk.FromString,
                )
        self.FetchModule = channel.unary_stream(
                '/remote_torch.RemoteTorch/FetchModule',
                request_serializer=remote__torch__pb2.Reference.SerializeToString,
                response_deserializer=remote__torch__pb2.Chunk.FromString,
                )
        self.DeleteDataset = channel.unary_unary(
                '/remote_torch.RemoteTorch/DeleteDataset',
                request_serializer=remote__torch__pb2.Reference.SerializeToString,
                response_deserializer=remote__torch__pb2.Empty.FromString,
                )
        self.DeleteModule = channel.unary_unary(
                '/remote_torch.RemoteTorch/DeleteModule',
                request_serializer=remote__torch__pb2.Reference.SerializeToString,
                response_deserializer=remote__torch__pb2.Empty.FromString,
                )
        self.AvailableModels = channel.unary_unary(
                '/remote_torch.RemoteTorch/AvailableModels',
                request_serializer=remote__torch__pb2.Empty.SerializeToString,
                response_deserializer=remote__torch__pb2.References.FromString,
                )
        self.AvailableDatasets = channel.unary_unary(
                '/remote_torch.RemoteTorch/AvailableDatasets',
                request_serializer=remote__torch__pb2.Empty.SerializeToString,
                response_deserializer=remote__torch__pb2.References.FromString,
                )
        self.AvailableDevices = channel.unary_unary(
                '/remote_torch.RemoteTorch/AvailableDevices',
                request_serializer=remote__torch__pb2.Empty.SerializeToString,
                response_deserializer=remote__torch__pb2.Devices.FromString,
                )
        self.AvailableOptimizers = channel.unary_unary(
                '/remote_torch.RemoteTorch/AvailableOptimizers',
                request_serializer=remote__torch__pb2.Empty.SerializeToString,
                response_deserializer=remote__torch__pb2.Optimizers.FromString,
                )
        self.Train = channel.unary_stream(
                '/remote_torch.RemoteTorch/Train',
                request_serializer=remote__torch__pb2.TrainConfig.SerializeToString,
                response_deserializer=remote__torch__pb2.Metric.FromString,
                )
        self.Test = channel.unary_stream(
                '/remote_torch.RemoteTorch/Test',
                request_serializer=remote__torch__pb2.TestConfig.SerializeToString,
                response_deserializer=remote__torch__pb2.Metric.FromString,
                )


class RemoteTorchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendDataset(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendModel(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchModule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AvailableModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AvailableDatasets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AvailableDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AvailableOptimizers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Test(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteTorchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendDataset': grpc.stream_unary_rpc_method_handler(
                    servicer.SendDataset,
                    request_deserializer=remote__torch__pb2.Chunk.FromString,
                    response_serializer=remote__torch__pb2.Reference.SerializeToString,
            ),
            'SendModel': grpc.stream_unary_rpc_method_handler(
                    servicer.SendModel,
                    request_deserializer=remote__torch__pb2.Chunk.FromString,
                    response_serializer=remote__torch__pb2.Reference.SerializeToString,
            ),
            'FetchDataset': grpc.unary_stream_rpc_method_handler(
                    servicer.FetchDataset,
                    request_deserializer=remote__torch__pb2.Reference.FromString,
                    response_serializer=remote__torch__pb2.Chunk.SerializeToString,
            ),
            'FetchModule': grpc.unary_stream_rpc_method_handler(
                    servicer.FetchModule,
                    request_deserializer=remote__torch__pb2.Reference.FromString,
                    response_serializer=remote__torch__pb2.Chunk.SerializeToString,
            ),
            'DeleteDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDataset,
                    request_deserializer=remote__torch__pb2.Reference.FromString,
                    response_serializer=remote__torch__pb2.Empty.SerializeToString,
            ),
            'DeleteModule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModule,
                    request_deserializer=remote__torch__pb2.Reference.FromString,
                    response_serializer=remote__torch__pb2.Empty.SerializeToString,
            ),
            'AvailableModels': grpc.unary_unary_rpc_method_handler(
                    servicer.AvailableModels,
                    request_deserializer=remote__torch__pb2.Empty.FromString,
                    response_serializer=remote__torch__pb2.References.SerializeToString,
            ),
            'AvailableDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.AvailableDatasets,
                    request_deserializer=remote__torch__pb2.Empty.FromString,
                    response_serializer=remote__torch__pb2.References.SerializeToString,
            ),
            'AvailableDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.AvailableDevices,
                    request_deserializer=remote__torch__pb2.Empty.FromString,
                    response_serializer=remote__torch__pb2.Devices.SerializeToString,
            ),
            'AvailableOptimizers': grpc.unary_unary_rpc_method_handler(
                    servicer.AvailableOptimizers,
                    request_deserializer=remote__torch__pb2.Empty.FromString,
                    response_serializer=remote__torch__pb2.Optimizers.SerializeToString,
            ),
            'Train': grpc.unary_stream_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=remote__torch__pb2.TrainConfig.FromString,
                    response_serializer=remote__torch__pb2.Metric.SerializeToString,
            ),
            'Test': grpc.unary_stream_rpc_method_handler(
                    servicer.Test,
                    request_deserializer=remote__torch__pb2.TestConfig.FromString,
                    response_serializer=remote__torch__pb2.Metric.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'remote_torch.RemoteTorch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RemoteTorch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendDataset(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/remote_torch.RemoteTorch/SendDataset',
            remote__torch__pb2.Chunk.SerializeToString,
            remote__torch__pb2.Reference.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendModel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/remote_torch.RemoteTorch/SendModel',
            remote__torch__pb2.Chunk.SerializeToString,
            remote__torch__pb2.Reference.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/remote_torch.RemoteTorch/FetchDataset',
            remote__torch__pb2.Reference.SerializeToString,
            remote__torch__pb2.Chunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchModule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/remote_torch.RemoteTorch/FetchModule',
            remote__torch__pb2.Reference.SerializeToString,
            remote__torch__pb2.Chunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/remote_torch.RemoteTorch/DeleteDataset',
            remote__torch__pb2.Reference.SerializeToString,
            remote__torch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteModule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/remote_torch.RemoteTorch/DeleteModule',
            remote__torch__pb2.Reference.SerializeToString,
            remote__torch__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AvailableModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/remote_torch.RemoteTorch/AvailableModels',
            remote__torch__pb2.Empty.SerializeToString,
            remote__torch__pb2.References.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AvailableDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/remote_torch.RemoteTorch/AvailableDatasets',
            remote__torch__pb2.Empty.SerializeToString,
            remote__torch__pb2.References.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AvailableDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/remote_torch.RemoteTorch/AvailableDevices',
            remote__torch__pb2.Empty.SerializeToString,
            remote__torch__pb2.Devices.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AvailableOptimizers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/remote_torch.RemoteTorch/AvailableOptimizers',
            remote__torch__pb2.Empty.SerializeToString,
            remote__torch__pb2.Optimizers.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/remote_torch.RemoteTorch/Train',
            remote__torch__pb2.TrainConfig.SerializeToString,
            remote__torch__pb2.Metric.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Test(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/remote_torch.RemoteTorch/Test',
            remote__torch__pb2.TestConfig.SerializeToString,
            remote__torch__pb2.Metric.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
