FROM nvcr.io/nvidia/pytorch:22.12-py3
WORKDIR /app
ENV DEBIAN_FRONTEND="noninteractive"
ENV BASTIONLAB_BUILD_AS_ROOT=1
RUN git clone "https://github.com/mithril-security/bastionlab.git"
WORKDIR /app/bastionlab/server/
RUN echo 'APT::Get::Install-Recommends "false";' > /etc/apt/apt.conf.d/00norecommends \
    && ./build.sh \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app/bastionlab/server
EXPOSE 50056
CMD ["make", "run"]
