# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# This file is auto generated by the github sync version manager workflow     #
# Do not modify it directly, use the github configuration variables instead.  #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #


__all__ = [
    "__torch_version__",
    "__torch_url__",
    "__torch_cxx11_url__",
    "__version__",
]
__torch_version__ = "1.13.1"
__torch_url__ = (
    "https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-"
    + __torch_version__
    + "%2Bcpu.zip"
)
__torch_cxx11_url__ = (
    "https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-"
    + __torch_version__
    + "%2Bcpu.zip"
)
__version__ = "0.3.7"
